---

- name: Network Getting Started First Playbook
  hosts: localhost
  tasks:
  
     - name: Run docker command
        community.docker.docker_container_exec:
        container: app_postgres_1
        command: /bin/bash -c "PGPASSWORD=philips1 psql --host=app_postgres_1 --dbname=philips_db --username=philips && \dt"
        chdir: /root

    - name: docker check
      command: docker ps
      register: result

    - name: Display
      debug:
        var: result.stdout
