---

- name: Network Getting Started First Playbook
  hosts: localhost
  tasks:

    - name: docker check
      command: docker ps
      register: result

    - name: Display
      debug:
        var: result.stdout
